"""CLI entrypoint for the V10/V11/V12 seed-migration generator.

`python -m seedgen [--strict]` -- loads the reviewed candidate JSON files plus a live
claim_type_aliases snapshot once, then writes V10__seed_entities.sql,
V11__seed_relationships.sql, and V12__seed_variant_claims.sql into
core-api/src/main/resources/db/migration/. A single orchestrated entrypoint (rather
than three independent scripts) so V11/V12 can never be generated against a stale
V10 entity list.

Idempotency note: ON CONFLICT DO NOTHING makes the *data* safe to re-apply, but this
generator regenerates the migration *files themselves* from scratch every run. That's
fine while V10-V12 don't exist yet / haven't been applied anywhere. Once Flyway has
applied these files to any shared environment, Flyway checksums them -- regenerating
and overwriting an already-applied file will break `flyway validate` for every other
environment. Corrections after first-apply must land as a new additive migration
(e.g. V12_1__..., following the V8_1-V8_4 precedent), never a re-run of this script
over an applied file.
"""

from dotenv import load_dotenv

load_dotenv()

import argparse
import json
from pathlib import Path

import psycopg2

import config
from extraction.claim_type_normalizer import load_alias_map

from seedgen import entities_gen, relationships_gen, variant_claims_gen
from seedgen.migration_writer import render_batched_insert, write_migration

OUTPUT_DIR = Path(__file__).resolve().parent.parent / "extraction" / "output"
MIGRATION_DIR = (
    Path(__file__).resolve().parent.parent.parent / "core-api" / "src" / "main" / "resources" / "db" / "migration"
)


def _load_json(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit non-zero if any floor conflict (Aphrodite parentage, Io parentage, "
        "Achilles death) is missing from the promoted variant_claims. Off by default so "
        "the generator stays usable mid-review.",
    )
    parser.add_argument(
        "--entities-file",
        type=Path,
        default=OUTPUT_DIR / "entities_candidates_confirmed_v1.json",
    )
    parser.add_argument(
        "--relationships-file",
        type=Path,
        default=OUTPUT_DIR / "relationships_candidates_cleaned.json",
    )
    parser.add_argument(
        "--variant-claims-file",
        type=Path,
        default=OUTPUT_DIR / "variant_claims_candidates.json",
    )
    parser.add_argument("--output-dir", type=Path, default=MIGRATION_DIR)
    args = parser.parse_args()

    entities = _load_json(args.entities_file)
    relationships = _load_json(args.relationships_file)
    variant_claims = _load_json(args.variant_claims_file)

    conn = psycopg2.connect(
        host=config.POSTGRES_HOST,
        port=config.POSTGRES_PORT,
        dbname=config.POSTGRES_DB,
        user=config.POSTGRES_USER,
        password=config.POSTGRES_PASSWORD,
    )
    alias_map = load_alias_map(conn)
    conn.close()

    entity_names = {e["name"] for e in entities}

    entity_rows = entities_gen.build_entity_rows(entities)
    relationship_rows = relationships_gen.build_relationship_rows(relationships, entity_names, alias_map)
    variant_claim_rows = variant_claims_gen.build_variant_claim_rows(variant_claims, entity_names, alias_map)

    write_migration(
        args.output_dir / "V10__seed_entities.sql",
        "-- Generated by ingestion/seedgen from entities_candidates_confirmed_v1.json (DEV-040).",
        render_batched_insert(
            "entities", entities_gen.COLUMNS, entity_rows, conflict_clause="ON CONFLICT (name) DO NOTHING"
        ),
    )
    write_migration(
        args.output_dir / "V11__seed_relationships.sql",
        "-- Generated by ingestion/seedgen from relationships_candidates_cleaned.json (post-B4 spot-check).\n"
        "-- Contested edges (parent_of/married_to/killed_by, >=2 competing sources)\n"
        "-- collapsed to one canonical edge per canonical_edge.py; the disagreement is\n"
        "-- recorded separately in V12 (ADR-007 Sec6).",
        render_batched_insert("relationships", relationships_gen.COLUMNS, relationship_rows),
    )
    write_migration(
        args.output_dir / "V12__seed_variant_claims.sql",
        "-- Generated by ingestion/seedgen from variant_claims_candidates.json.\n"
        "-- Only trust_tier=1 (human-reviewed, promoted) rows are included.",
        render_batched_insert("variant_claims", variant_claims_gen.COLUMNS, variant_claim_rows),
    )

    print(f"V10: {len(entity_rows)} entities", flush=True)
    print(f"V11: {len(relationship_rows)} relationships (of {len(relationships)} candidates)", flush=True)
    print(f"V12: {len(variant_claim_rows)} variant_claims (of {len(variant_claims)} candidates)", flush=True)

    floor_warnings = variant_claims_gen.check_floor_conflicts(variant_claims, entity_names, alias_map)
    for w in floor_warnings:
        print(f"[WARN] {w}", flush=True)
    if args.strict and floor_warnings:
        raise SystemExit(f"{len(floor_warnings)} floor conflict(s) missing -- see warnings above")

    near_dup_warnings = variant_claims_gen.warn_near_duplicate_claim_types(variant_claims)
    for w in near_dup_warnings[:20]:
        print(f"[WARN] {w}", flush=True)
    if len(near_dup_warnings) > 20:
        print(f"[WARN] ... and {len(near_dup_warnings) - 20} more near-duplicate claim_type groups", flush=True)


if __name__ == "__main__":
    main()
