CREATE USER zeus_app WITH PASSWORD 'app_password';
GRANT CONNECT ON DATABASE blamezeus TO zeus_app;
GRANT USAGE ON SCHEMA public TO zeus_app;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO zeus_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO zeus_app;
