#!/usr/bin/env python3
"""Regenerate the Index block in `docs/DEVIATIONS.md` from the entry headings themselves.

The index exists because DEVIATIONS.md outgrew a single read (DEV-131): closed phases are
archived under `docs/deviations/`, and the index is what keeps every inline
`[DEVIATED - see DEVIATIONS.md #DEV-NNN]` marker resolving without being rewritten.

A hand-maintained index drifts, which is this repo's most-repeated defect (DEV-128 finding 3,
DEV-129 correction 2, the "a recorded figure names its construction" rule). So the index is
generated from the `### DEV-NNN — …` headings and never edited by hand.

    python3 scripts/deviations-index.py            # rewrite the block in place
    python3 scripts/deviations-index.py --check    # exit 1 if the block is stale

Adding an entry: append it to DEVIATIONS.md as usual, then run this. Closing a phase: move its
entries verbatim into `docs/deviations/<phase>.md`, add the file to PHASES below, then run this.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

DOCS = pathlib.Path(__file__).resolve().parent.parent / "docs"
LIVE = DOCS / "DEVIATIONS.md"

# Archived phases, oldest first. `None` means "the live file".
PHASES: list[tuple[str, str | None]] = [
    ("Phase 1 — DEV-001…DEV-057", "deviations/phase1.md"),
    ("Phase 2 — DEV-058 onward", None),
]

BEGIN = "<!-- INDEX:BEGIN — generated by scripts/deviations-index.py; do not edit by hand -->"
END = "<!-- INDEX:END -->"

# DEV-005's heading is struck through (`### ~~DEV-005 — …~~ RESOLVED`). It is a real entry and
# must stay indexed, so the pattern tolerates the strikethrough markers.
ENTRY_RE = re.compile(r"(?m)^### (?:~~)?(DEV-(\d+)) — (.*?)(?:~~ ?.*)?$")
SECTION_RE = re.compile(r"(?m)^## (?!#)(?!Index$)(.*)$")

# Ids that were never written. Listed so a reader can tell a deliberate gap from a lost entry.
RESERVED = {
    16: "reserved by ADR-009's action items, never written",
    17: "reserved by ADR-010; the work landed as DEV-060",
    106: "deliberately unclaimed (TODO2.md Stage P4)",
    111: "folded into DEV-110 before it was written",
}


def gh_anchor(heading: str) -> str:
    """GitHub's heading-slug algorithm.

    Anchors come from the FULL heading text, not the id — `#dev-001` does not resolve,
    `#dev-001--kotlin-version-19x--2321` does. Deriving it keeps archived bodies verbatim.
    """
    s = re.sub(r"[^\w\s-]", "", heading.strip().lower(), flags=re.UNICODE)
    return re.sub(r"\s+", "-", s).strip("-")


def hook(title: str, limit: int = 118) -> str:
    t = title.split(" (see ")[0].split(" — see ")[0].strip()
    return t if len(t) <= limit else t[: limit - 1].rsplit(" ", 1)[0] + "…"


def render(body: str, link: str) -> tuple[str, list[int]]:
    lines: list[str] = []
    ids: list[int] = []
    current = None
    sections = [(m.start(), m.group(1)) for m in SECTION_RE.finditer(body)]
    for m in ENTRY_RE.finditer(body):
        sec = next((s for pos, s in reversed(sections) if pos < m.start()), "?")
        if sec != current:
            current = sec
            lines.append(f"\n**{sec}**\n")
        heading = m.group(0)[len("### ") :]
        mark = " *(resolved)*" if heading.startswith("~~") else ""
        lines.append(
            f"- [{m.group(1)}]({link}#{gh_anchor(heading)}) — {hook(m.group(3))}{mark}"
        )
        ids.append(int(m.group(2)))
    return "\n".join(lines).strip(), ids


def build() -> str:
    blocks: list[str] = []
    all_ids: list[int] = []
    for label, rel in PHASES:
        path = LIVE if rel is None else DOCS / rel
        block, ids = render(path.read_text(encoding="utf-8"), rel or "")
        all_ids += ids
        state = "live" if rel is None else "archived"
        open_attr = " open" if rel is None else ""
        blocks.append(
            f"<details{open_attr}>\n<summary><strong>{label}</strong> "
            f"({state}, {len(ids)} entries)</summary>\n\n{block}\n\n</details>"
        )

    dupes = {i for i in all_ids if all_ids.count(i) > 1}
    if dupes:
        sys.exit(f"duplicate DEV ids across files: {sorted(dupes)}")
    gaps = sorted(set(range(1, max(all_ids) + 1)) - set(all_ids))
    if set(gaps) != set(RESERVED):
        sys.exit(f"id gaps changed: {gaps} (expected {sorted(RESERVED)}) — update RESERVED")

    reserved = "; ".join(f"**DEV-{i:03d}** {why}" for i, why in sorted(RESERVED.items()))
    return (
        f"{BEGIN}\n\n"
        f"{len(all_ids)} entries, oldest section first. Archived phases keep their entries "
        f"**verbatim**; the `DEV-NNN` counter is global and never forks, so an id identifies an "
        f"entry regardless of which file holds it. That is what lets the ~340 inline "
        f"`[DEVIATED - see DEVIATIONS.md #DEV-NNN]` markers across the repo keep resolving "
        f"through this index without being rewritten (DEV-131).\n\n"
        f"*Unwritten ids, so a gap reads as deliberate rather than lost:* {reserved}.\n\n"
        + "\n\n".join(blocks)
        + f"\n\n{END}"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the index is stale")
    args = ap.parse_args()

    text = LIVE.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        sys.exit(f"index markers not found in {LIVE}")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = head + build() + tail

    if args.check:
        if new != text:
            print("DEVIATIONS.md index is stale — run scripts/deviations-index.py", file=sys.stderr)
            return 1
        print("index up to date")
        return 0

    LIVE.write_text(new, encoding="utf-8")
    print(f"index regenerated in {LIVE.relative_to(LIVE.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
